import { PrismaClient } from '@prisma/client';

export async function seedProductVariants(prisma: PrismaClient) {
  await prisma.productVariant.createMany({
    data: [
      {
        productVariantId: 'tops-t-shirts-001-beige-s',
        productId: 'tops-t-shirts-001',
        colorId: 'beige',
        sizeId: 's',
        SKU: '100200512001',
        stock: 100,
        soldQuantity: 30,
      },
      {
        productVariantId: 'tops-t-shirts-001-black-xl',
        productId: 'tops-t-shirts-001',
        colorId: 'black',
        sizeId: 'xl',
        SKU: '100200512006',
        stock: 24,
        soldQuantity: 15,
      },
      {
        productVariantId: 'tops-t-shirts-002-black-m',
        productId: 'tops-t-shirts-002',
        colorId: 'black',
        sizeId: 'm',
        SKU: '100196998007_3ATSV2143',
        stock: 30,
        soldQuantity: 50,
      },
      {
        productVariantId: 'tops-t-shirts-003-pink-m',
        productId: 'tops-t-shirts-003',
        colorId: 'pink',
        sizeId: 'm',
        SKU: '100196997002_3ATSN0343',
        stock: 30,
        soldQuantity: 50,
      },
      {
        productVariantId: 'tops-t-shirts-003-pink-l',
        productId: 'tops-t-shirts-003',
        colorId: 'pink',
        sizeId: 'l',
        SKU: '100196997001_3ATSN0343',
        stock: 30,
        soldQuantity: 50,
      },
      {
        productVariantId: 'tops-t-shirts-004-blue-l',
        productId: 'tops-t-shirts-004',
        colorId: 'blue',
        sizeId: 'l',
        SKU: '100196996001_3ATSN0143',
        stock: 40,
        soldQuantity: 10,
      },
      {
        productVariantId: 'tops-t-shirts-005-black-s',
        productId: 'tops-t-shirts-005',
        colorId: 'black',
        sizeId: 's',
        SKU: '100196995001_3ATSB2243',
        stock: 13,
        soldQuantity: 11,
      },
      {
        productVariantId: 'tops-t-shirts-006-brown-xl',
        productId: 'tops-t-shirts-006',
        colorId: 'brown',
        sizeId: 'xl',
        SKU: '100196994005_3ATSB0443',
        stock: 13,
        soldQuantity: 9,
      },
      {
        productVariantId: 'tops-t-shirts-007-green-xl',
        productId: 'tops-t-shirts-007',
        colorId: 'green',
        sizeId: 'xl',
        SKU: '100196980001_3ATSV0943',
        stock: 13,
        soldQuantity: 16,
      },
      {
        productVariantId: 'tops-t-shirts-008-red-xxl',
        productId: 'tops-t-shirts-008',
        colorId: 'red',
        sizeId: 'xxl',
        SKU: '100196581006_3ATSV1143',
        stock: 10,
        soldQuantity: 25,
      },
      {
        productVariantId: 'tops-t-shirts-009-purple-s',
        productId: 'tops-t-shirts-009',
        colorId: 'purple',
        sizeId: 's',
        SKU: '100196579001_3ATSV0243',
        stock: 10,
        soldQuantity: 2,
      },
      {
        productVariantId: 'tops-t-shirts-010-beige-s',
        productId: 'tops-t-shirts-010',
        colorId: 'beige',
        sizeId: 's',
        SKU: '100196572001_3ATSE0243',
        stock: 10,
        soldQuantity: 7,
      },
    ],
    skipDuplicates: true, // Bỏ qua các bản ghi đã tồn tại nếu bạn không muốn xóa
  });
}
